const express=require('express')
const TaskController=require('../controllers/TaskController')
const route=express.Router()
route.get("/",TaskController.getAllTasks)
route.get("/:id",TaskController.getTaskById)
route.post("/",TaskController.createTask)
route.put("/teacher",TaskController.updateTaskTeacher)
route.put("/student",TaskController.updateTaskStudent)
// route.put("/",TaskController.updateTask)
route.delete("/",TaskController.deleteTask)
module.exports=route